dataset: "Adience"
method: UNIORDEnt
dist_func: 'Normal'    # choose from here: torch.distributions
root_dir: /data/or/data
data_folds: 5
data_splits: 1
data_images: /data/or/data/aligned
output_dir: Adience
model_type: null
not_weigted: true
ordinal_input_dim: 1000
train_batch_size: 64
val_batch_size: 64
test_batch_size: 64
train_workers: 8
val_workers: 8
test_workers: 8
max_epochs: 100
lr: 1e-4
lr_sched: '40'
wd: 1e-5
gamma: 0.1
num_classes: 8
checkpoint_on: 'val_mae'
min_sigma: 0.1
bins_limit: 1.
resume_from_checkpoint: null
fold: null
split: null
output_logits: false
accelerator: "gpu"
devices: 1
checkpoint_callback: true
check_val_every_n_epoch: 1
error_analysis: false
val_boost: null