dataset: 'HCI'
method: UNIORDEnt
dist_func: 'Normal'    # choose from here: torch.distributions
data_root: /data/or/data/historical-color-image-decade
data_images: /data/or/data/HistoricalColor-ECCV2012/data/imgs/decade_database
data_splits: 10
data_folds: 1
output_dir: HCI
model_type: null
not_weigted: true
ordinal_input_dim: 1000
train_batch_size: 16
val_batch_size: 16
test_batch_size: 1
train_workers: 8
val_workers: 2
test_workers: 1
max_epochs: 500
min_epochs: 500
lr: 1e-4
lr_sched: '100,300'
gamma: 0.1
wd: 1e-3
num_classes: 5
min_sigma: 0.1
bins_limit: 1.
checkpoint_on: 'val_mae'
resume_from_checkpoint: null
fold: null
split: null
output_logits: false
accelerator: "gpu"
devices: 1
check_val_every_n_epoch: 1
checkpoint_callback: true
error_analysis: false
val_boost: 3

