dataset: "MedMNISTOrdinal"
method: UNIORDEnt
medmnist_type: "RetinaMNIST"
dist_func: 'Normal'    # choose from here: torch.distributions
root_dir: 'medmnist_data'
data_folds: 1
data_splits: 10
ordinal_input_dim: 1000
output_dir: MedMNISTOrdinal
model_type: null
not_weigted: True
train_batch_size: 16
val_batch_size: 16
test_batch_size: 16
train_workers: 8
val_workers: 8
test_workers: 2
max_epochs: 100
lr: 1e-4
lr_sched: '80,90'
wd: 1e-4
gamma: 0.1
num_classes: 5
checkpoint_on: 'val_mae'
min_sigma: 0.1
bins_limit: 1.
resume_from_checkpoint: null
fold: null
split: null
output_logits: False
accelerator: "gpu"
devices: 1
checkpoint_callback: True
check_val_every_n_epoch: 1
error_analysis: False
val_boost: null